name: Test

on: pull_request

jobs:
  checking:
    runs-on: ubuntu-latest

    name: Testing
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: TypeScript Check
        run: tsc
      - name: Lint Check
        run: yarn lint
      - name: Runs Jest
        run: yarn test
      - name: Runs Coverage Check
        run: yarn coverage
